repos:
  - repo: local
    hooks:
      - id: ruff-linter
        name: Linter
        entry: uv run ruff check
        language: system
        types: [python]
        fail_fast: true

      - id: ruff-formatter
        name: Formatter
        entry: uv run ruff format --diff
        language: system
        types: [python]
        fail_fast: true

      - id: pyright
        name: Type checker
        entry: uv run pyright
        language: system
        types: [python]
        fail_fast: true
