name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.10"
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Python packages
        run: uv sync --locked --dev
        shell: bash

      - name: Linter
        run: uv run ruff check
        shell: bash

      - name: Formatter
        run: uv run ruff format --check
        shell: bash

      - name: Type checker
        run: uv run pyright
        shell: bash

      - name: Unit tests
        run: uv run pytest tests/unit
        shell: bash

  release:
    runs-on: ubuntu-latest
    needs: continous-integration
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.3.2/install.sh | sh
        shell: bash

      - name: Install Hatch
        run: uv pip install --system hatch
        shell: bash

      - name: Build package
        run: hatch build
        shell: bash

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
