name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    env:
      UV_NO_SYNC: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          version: "0.8.15"
          python-version: ${{ matrix.python-version }}

      - name: Install Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Pre-commit
        run: uv run -- pre-commit run --all-files
        shell: bash

      - name: Unit tests
        run: uv run -- pytest tests/unit
        shell: bash

  release:
    runs-on: ubuntu-latest
    needs: continous-integration
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          version: "0.8.15"

      - name: Install Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: .python-version

      - name: Build package
        run: uv build
        shell: bash

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
        shell: bash
