name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    env:
      UV_PYTHON: ${{ matrix.python-version }}
      UV_NO_SYNC: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Unit tests
        run: uv run pytest tests/unit
        shell: bash

  release:
    runs-on: ubuntu-latest
    needs: continous-integration
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Build package
        run: uv build
        shell: bash

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
        shell: bash
