name: Pull request

on:
  pull_request:
    branches:
        - main

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        run: pip install --root-user-action=ignore uv
        shell: bash

      - name: Install Python packages
        run: uv pip install --system --requirement pyproject.toml --requirement requirements-dev.txt
        shell: bash
      
      - name: Run linter and formatter
        run: python -m ruff check .
        shell: bash
      
      - name: Run type checker
        run: python -m pyright .
        shell: bash

      - name: Run unit tests
        run: python -m pytest tests/unit
        shell: bash
  
  release:
    runs-on: ubuntu-latest
    needs: continous-integration
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        run: pip install --root-user-action=ignore uv
        shell: bash

      - name: Install Hatch
        run: uv pip install --system hatch
        shell: bash
      
      - name: Build package
        run: hatch build
        shell: bash
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
